development:
  bucket: toribaa_port
  access_key_id: AKIAJZX6DS63XQWWYJUQ
  secret_access_key: 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
test:
  bucket: toribaa_port
  access_key_id: AKIAJZX6DS63XQWWYJUQ
  secret_access_key: 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
production:
  bucket: toribaa_port
  access_key_id: AKIAJZX6DS63XQWWYJUQ
  secret_access_key: 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